url: https://mayankgupta.in
baseurl: 

# Site settings
title: Mayank Gupta
email: me@mayakngupta.in
description: "Things I learned then made, things that made me learn and things that I made to learn."


# Team names, titles and social links
people:
- name: Mayank Gupta
  pic: 1
  position: Software Developer and Data Scientist
  social:
    - title: twitter
      url: https://twitter.com/techfreakworm
    - title: linkedin
      url: https://www.linkedin.com/in/techfreakworm/
    - title: stack-overflow
      url: https://stackoverflow.com/users/5230057/mayank-gupta
    - title: medium
      url: https://medium.com/@techfreakworm


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: github
#     url: http://github.com/jekyll
#   - title: linkedin
#     url: http://linkedin.com/techfreakworm
#   - title: medium
#     url: http://medium.com/techfreakworm

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty